### ISSUE TITLE
QtWebKitWidgets

### ISSUE THREAD

**Issue by selfus** [jjgomera/pychemqt#12]
Having the following error:

> ImportError: cannot import name 'QtWebKitWidgets'

It seems QtWebKitWidgets got deprecated, on version 5.5/5.6 and probably replaced with QtWebEngineWidgets

**Comment by jjgomera** [comment]
You are right. I'm using pyqt v.5.5 and the QtWebKitWidgets is available, but is deprecated and in version 5.6 is removed.
I've removed that dependence in code, it wasn't necessary.
