### ISSUE TITLE
Trying to run pychemqt after install

### ISSUE THREAD

**Issue by Plancalkuele** [jjgomera/pychemqt#18]
Hi there,
I installed pychemqt in a miniconda environment via `python setup.py install`.

When I try to run pychemqt via `python pychemqt.py` I receive the following error:

`QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Traceback (most recent call last):
  File "pychemqt.py", line 150, in <module>
    mayor, minor, corr = map(int, matplotlib.__version__.split("."))
ValueError: invalid literal for int() with base 10: '0rc2'`

Fixed this by installing matplotlib via `conda install matplotlib`.

**Comment by jjgomera** [comment]
So, finally does it run fine?
