### ISSUE TITLE
Can not find the LibraryLocation

### ISSUE THREAD

**Issue by diyaragirman** [jjgomera/pychemqt#21]
Hello,

that is a very useful program. I have built everything just like in the readme and the .travis.yml described. After runing the "pychemqt.py" the following error occurs:

  File "pychemqt.py", line 102, in <module>
    path = QtCore.QLibraryInfo.path(QtCore.QLibraryInfo.LibraryPath.TranslationsPath)
AttributeError: type object 'LibraryLocation' has no attribute 'TranslationsPath'

What should I do to avoid this Error?

**Comment by jjgomera** [comment]
What OS are you using,  and qt version?

**Comment by diyaragirman** [comment]
Im using 64 bit windows 10 OS and the pyqt5. I think it is because of the OS. My friend have cloned the repository on his Mac and he was aible to execute the files without any problems. Do you have the same experience with other users of this project?

**Comment by jjgomera** [comment]
No, I don't. In fact i don't have any windows to check your error...

**Comment by diyaragirman** [comment]
At the moment I'm going this way to clone the repository:
Create a new folder with the name _ProjectGithubselfedit4_ in C:\Users\USERNAME
Then run the anaconda shell. (The Commands in the anaconda shell are beginning with " >> " )

Change the directory to the new folder
>> cd ProjectGithubselfedit4
create a new environment with the name test_envX in the python-version 3.8
>> conda create -n test_envX python=3. 8 
Activate the new environment
>> conda activate test_envX 
Clone the repository from github
>>git clone https://github.com/jjgomera/pychemqt.git 
change in the new created folder pychemqt, which was automatically- created due to the cloning
>> cd pychemqt 
Install all needed requirements
>> pip install **.** 
Running the setup.py module in the pychemqt folder
>> python setup.py install 
show all packages which are in the environment
>>conda list
install all missing packages with:
>>conda install Pyqt 
>> conda install numpydoc 
>>conda install sphinx_rtd_theme 
>> conda install coveralls 
>>conda install codecov 
Test the initilation.py module in the tests folder
>>python tests/initialization.py 
Test alle moduls in the tests folder
>>coverage run tests/ 
run the main module
>>python pychemqt.py

After this last Run-command in the commando shell, I`m getting the following error, where the last Entrance is maybe the most interested:

freesteam could not be found, freesteam thermal option disabled
CoolProp could not be found, coolprop thermal option disabled
refprop could not be found, refprop thermal option disabled
openbabel could not be found, graphic formula disabled
ezodf could not be found, openoffice/libreoffice interaction disabled
openpyxl could not be found, Microsoft Excel 2007/2010 interaction disabled
xlwt could not be found, Microsoft Excel 97/2000/XP/2003 interaction disabled
icu could not be found, Unicode collation algorithm for improved string sorting disabled
reportlab could not be found, Pdf report exporting disabled
Qsci could not be found, Qscintilla custom module editor disabled
Traceback (most recent call last):
  File "pychemqt.py", line 356, in <module>
    import equipment  # noqa
  File "C:\Users\AgirmaBD\ProjectGithubselfedit4\pychemqt\equipment\__init__.py", line 27, in <module>
    from equipment import UI_divider
  File "C:\Users\AgirmaBD\ProjectGithubselfedit4\pychemqt\equipment\UI_divider.py", line 31, in <module>
    from equipment.parents import UI_equip
  File "C:\Users\AgirmaBD\ProjectGithubselfedit4\pychemqt\equipment\parents.py", line 36, in <module>
    from tools.costIndex import indiceBase, indiceActual
  File "C:\Users\AgirmaBD\ProjectGithubselfedit4\pychemqt\tools\costIndex.py", line 33, in <module>
    from UI.widgets import Entrada_con_unidades
  File "C:\Users\AgirmaBD\ProjectGithubselfedit4\pychemqt\UI\widgets.py", line 55, in <module>
    from lib.corriente import Corriente
  File "C:\Users\AgirmaBD\ProjectGithubselfedit4\pychemqt\lib\corriente.py", line 37, in <module>
    from lib import EoS, mEoS, gerg, iapws97, freeSteam, refProp, coolProp
  File "C:\Users\AgirmaBD\ProjectGithubselfedit4\pychemqt\lib\gerg.py", line 50, in <module>
    class GERG(object):
  File "C:\Users\AgirmaBD\ProjectGithubselfedit4\pychemqt\lib\gerg.py", line 70, in GERG
    Fij = pickle.load(open(os.path.join(os.environ["pychemqt"], "dat",
**ValueError: could not convert string to float**

Maybe because the code was writtingen on an different OS than Windows the error occurs.

**Comment by jjgomera** [comment]
It shouldn't be for that, try with last commit. I'm trying to remove any pickling save data, do now for that library, partially implemented

**Comment by diyaragirman** [comment]
The last commit helped a lot. It is working now.
