### ISSUE TITLE
Hi, do you know how to run on windows 10 with python 3.xx

### ISSUE THREAD

**Issue by bkt92** [jjgomera/pychemqt#4]
Because of freesteam software, so I can't run this software on windows.
Hope ypu can guide me how to run it ?
Thanks.

**Comment by jjgomera** [comment]
Hi,
First at all, install mandatory dependences, see README.rst file, python3, pyqt5, python-scipy, python-numpy and python-matplotlib.
The optional dependences (like freesteam) there isn't necessary to start to use pychemqt
Download pychemqt code, for example zipped from here: https://github.com/jjgomera/pychemqt/archive/master.zip
