### ISSUE TITLE
debug:sqlite3.OperationalError: no such table: compuestos

### ISSUE THREAD

**Issue by thermalogic** [jjgomera/pychemqt#6]
File "/home/cmh/mygit/pychemqt/lib/sql.py", line 48, in <module>
    databank_Custom.execute("SELECT COUNT(*) AS Total FROM compuestos")
sqlite3.OperationalError: no such table: compuestos

change sql.py

   databank_Custom_name = conf_dir +'databank.db'

to 

databank_Custom_name = conf_dir +'dat'+os.sep+'databank.db'

**Comment by jjgomera** [comment]
Hi, that problem is from a old bug, remove the file /home/cmh/.pychemqt/databank.db and start pychemqt again.
conf_dir is that folder in your system, and there pychemqt save its config files, that databank is for save custom component defined by user.

**Comment by thermalogic** [comment]
Thanks
